### ISSUE TITLE
Released executable showing as trojan virus

### ISSUE THREAD

**Issue by emshdev** [smh0505/rhythm_relay#1]
Your rhythm_relay release v1.0 was detected by Windows Defender as Trojan:Win32/Wacatac.B!ml
I have seen the code and there was nothing to be "highly dangerous ransomware" as Windows Defender shows.
I was guessing maybe the program you used to bake the script into an executable might be the one suspicious because when I tried baking my own executive using pyinstaller the file's size was kind of different with yours (2.87megabytes with no options, 21.8megabytes with option --onefile)
Would you mind checking on the programs you used?
![image](https://user-images.githubusercontent.com/89697004/182665616-c9ebe0e4-4251-4ba5-9f0f-3d7f854bc674.png)
![image](https://user-images.githubusercontent.com/89697004/182667463-e205897d-f697-4490-aad5-aa78f25eebae.png)
![image](https://user-images.githubusercontent.com/89697004/182668051-fdece9e2-ae65-4bf5-be08-a43b9ab70e94.png)
![image](https://user-images.githubusercontent.com/89697004/182670337-cd4944e4-e182-4ec3-91c4-def912e644a8.png)

**Comment by emshdev** [comment]
[baked.zip](https://github.com/smh0505/rhythm_relay/files/9253729/baked.zip)
Here are the files I compiled myself in case you need to check on them.

**Comment by smh0505** [comment]
[main.zip](https://github.com/smh0505/rhythm_relay/files/9256288/main.zip)
I have recompiled the file to .exe using pyinstaller.
If this one is not detected as a virus, then the problem would be with the auto-py-to-exe, one I used previously.

**Comment by emshdev** [comment]
I still have no luck. The executable is still considered virus to Windows and is constantly getting removed. Would it be possible that the files I compiled (baked.zip) are getting isolated on your PC too?

**Comment by emshdev** [comment]
> [main.zip](https://github.com/smh0505/rhythm_relay/files/9256288/main.zip) I have recompiled the file to .exe using pyinstaller. If this one is not detected as a virus, then the problem would be with the auto-py-to-exe, one I used previously.

https://github.com/SJang1/2021-korea-covid-19-remaining-vaccine-macro/pull/573 I think I might have found the suspicious one. There was a python-based macro going through the same issues because the project was using pyinstaller (auto-py-to-exe seems like it was based on pyinstaller anyways.)
They used nuitka as the packager and had the problem solved. How about trying them out?

**Comment by smh0505** [comment]
[Rhythm Relay.zip](https://github.com/smh0505/rhythm_relay/files/9258696/Rhythm.Relay.zip)
Would you check for this one then?
This one is compiled with nuitka, using no option.

**Comment by emshdev** [comment]
> [Rhythm Relay.zip](https://github.com/smh0505/rhythm_relay/files/9258696/Rhythm.Relay.zip) Would you check for this one then? This one is compiled with nuitka, using no option.

I am happy to tell you that Windows defender did not show the files as trojans. Although my python3 version is different(3.10.6) and the executable did not work because of the dependencies.

**Comment by emshdev** [comment]
Issue resolved as video shows
https://www.twitch.tv/videos/1551860441?t=04h29m30s
Waiting for new release

**Comment by smh0505** [comment]
Maybe I need to put --onefile option at the end for the file to be executable.
Anyway, thank you for the help.
